/*
 * List of U.S national parks, along with NPS park codes, audio filenames, and Wikipedia topic.
 */

module.exports =
[
	{"parkName":"Denali","parkCode":"dena","audio":"snow.mp3"},
	{"parkName":"Gates of the Arctic","parkCode":"gaar","audio":"hiking.mp3"},
	{"parkName":"Glacier Bay","parkCode":"glba","audio":"lake.mp3"},
	{"parkName":"Katmai","parkCode":"katm","audio":"water.mp3"},
	{"parkName":"Kenai Fjords","parkCode":"kefj","audio":"lake.mp3"},
	{"parkName":"Kobuk Valley","parkCode":"kova","audio":"river.mp3"},
	{"parkName":"Lake Clark","parkCode":"lacl","audio":"lake.mp3"},
	{"parkName":"Wrangell St. Elias","parkCode":"wrst","audio":"hiking.mp3"},
	{"parkName":"Grand Canyon","parkCode":"grca","audio":"hiking.mp3"},
	{"parkName":"Petrified Forest","parkCode":"pefo","audio":"hiking.mp3"},
	{"parkName":"Saguaro","parkCode":"sagu","audio":"hiking.mp3"},
	{"parkName":"Hot Springs","parkCode":"hosp","audio":"water.mp3"},
	{"parkName":"Channel Islands","parkCode":"chis","audio":"ocean.mp3"},
	{"parkName":"Death Valley","parkCode":"deva","audio":"hiking.mp3"},
	{"parkName":"Joshua Tree","parkCode":"jotr","audio":"hiking.mp3"},
	{"parkName":"Kings Canyon","parkCode":"seki","audio":"hiking.mp3"},
	{"parkName":"Lassen Volcanic","parkCode":"lavo","audio":"boilingmud.mp3"},
	{"parkName":"Pinnacles","parkCode":"pinn","audio":"hiking.mp3"},
	{"parkName":"Redwood","parkCode":"redw","audio":"river.mp3"},
	{"parkName":"Sequoia","parkCode":"seki","audio":"hiking.mp3"},
	{"parkName":"Black Canyon of the Gunnison","parkCode":"blca","audio":"hiking.mp3"},
	{"parkName":"Great Sand Dunes","parkCode":"grsa","audio":"brook.mp3"},
	{"parkName":"Mesa Verde","parkCode":"meve","audio":"hiking.mp3"},
	{"parkName":"Rocky Mountain","parkCode":"romo","audio":"hiking.mp3"},
	{"parkName":"Everglades","parkCode":"ever","audio":"paddling.mp3"},
	{"parkName":"Biscayne","parkCode":"bisc","audio":"paddling.mp3"},
	{"parkName":"Dry Tortugas","parkCode":"drto","audio":"ocean.mp3"},
	{"parkName":"Haleakala","parkCode":"hale","audio":"hiking.mp3"},
	{"parkName":"Hawaii Volcanoes","parkCode":"havo","audio":"kilauea.mp3"},
	{"parkName":"Mammoth Cave","parkCode":"maca","audio":"cave.mp3"},
	{"parkName":"Acadia","parkCode":"acad","audio":"maine.mp3"},
	{"parkName":"Isle Royale","parkCode":"isro","audio":"lake.mp3"},
	{"parkName":"Voyageurs","parkCode":"voya","audio":"lake.mp3"},
	{"parkName":"Glacier","parkCode":"glac","audio":"lake.mp3"},
	{"parkName":"Great Basin","parkCode":"grba","audio":"cave.mp3"},
	{"parkName":"Carlsbad Caverns","parkCode":"cave","audio":"bats.mp3"},
	{"parkName":"Great Smoky Mountains","parkCode":"grsm","audio":"bearsmoky.mp3"},
	{"parkName":"Theodore Roosevelt","parkCode":"thro","audio":"hiking.mp3"},
	{"parkName":"Cuyahoga Valley","parkCode":"cuva","audio":"hiking.mp3"},
	{"parkName":"Crater Lake","parkCode":"crla","audio":"lake.mp3"},
	{"parkName":"Congaree","parkCode":"cong","audio":"river.mp3"},
	{"parkName":"Badlands","parkCode":"badl","audio":"hiking.mp3"},
	{"parkName":"Wind Cave","parkCode":"wica","audio":"cave.mp3"},
	{"parkName":"Big Bend","parkCode":"bibe","audio":"river.mp3"},
	{"parkName":"Guadalupe Mountains","parkCode":"gumo","audio":"hiking.mp3"},
	{"parkName":"Arches","parkCode":"arch","audio":"hiking.mp3"},
	{"parkName":"Bryce Canyon","parkCode":"brca","audio":"hiking.mp3"},
	{"parkName":"Capitol Reef","parkCode":"care","audio":"hiking.mp3"},
	{"parkName":"Canyonlands","parkCode":"cany","audio":"river.mp3"},
	{"parkName":"Shenandoah","parkCode":"shen","audio":"hiking.mp3"},
	{"parkName":"Mount Rainier","parkCode":"mora","audio":"hiking.mp3"},
	{"parkName":"North Cascades","parkCode":"noca","audio":"bearnorthcascades.mp3"},
	{"parkName":"Olympic","parkCode":"olym","audio":"hiking.mp3"},
	{"parkName":"Yellowstone","parkCode":"yell","audio":"geyser.mp3"},
	{"parkName":"Yosemite","parkCode":"yose","audio":"waterfall.mp3"},
	{"parkName":"Zion","parkCode":"zion","audio":"hiking.mp3"},
	{"parkName":"Virgin Islands","parkCode":"viis","audio":"lake.mp3"},
	{"parkName":"Grand Teton","parkCode":"grte","audio":"river.mp3"},
	{"parkName":"American Samoa","parkCode":"npsa","audio":"ocean.mp3"}
];
